services:
  - type: web
    name: bg-eraser
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      memory: 2048
      cpu: 2
